## name: Hello World Workflow

on:
  schedule:
    - cron: '*/30 * * * *'  # This line correctly schedules the workflow to run every 30 minutes
  workflow_dispatch:  # This line correctly allows for manual triggering of the workflow via GitHub UI

jobs:
  hello_world_job:
    runs-on: ubuntu-latest  # Specifies that the job runs on the latest Ubuntu runner

    steps:
    - name: Check out code
      uses: actions/checkout@v2  # Checks out your repository under $GITHUB_WORKSPACE, so your job can access it

    - name: Set up Python
      uses: actions/setup-python@v4  # Sets up a specific version of Python
      with:
        python-version: '3.x'  # Specifies the Python version to set up

    - name: Run hello.py
      run: python hello.py  # Executes the hello.py script